name: publish/conda
run-name: ${{
    format(
      '[{0}] publish/conda{1}',
      (github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_branch) ||
      (github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch) ||
      (github.event.workflow_run.event == 'release' && github.event.workflow_run.head_branch) ||
      github.event_name,
      (github.event.action == 'requested' && ' (requested)') || ''
    )
  }}


on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
  workflow_run:
    workflows: ['build/conda']
    types:
      - completed
      - requested


permissions:
  statuses: write


jobs:
  publish_package:
    name: Publish Conda Package
    uses: energy-quants/.github/.github/workflows/publish-conda.yml@main
    secrets:
      token: ${{ secrets.CI_PACKAGES }}
